# Generated by Django 4.2.11 on 2024-05-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contaxt',
            new_name='Contact',
        ),
    ]
